### ISSUE TITLE
widget doesn't show properly

### ISSUE THREAD

**Issue by ghost** [Gictorbit/victorconky#2]

**Comment by brucehankins** [comment]
Have you gotten an answer on this? I'm having the same issue
![image](https://user-images.githubusercontent.com/65924990/85549862-6637d380-b5ee-11ea-82a8-86c41696e8ac.png)

**Comment by Gictorbit** [comment]
I made some change
please try `install.sh`
your path is wrong the correct one is `~/.conky/victoryConky` not `~/.conky/victoryConky/victoryConky`
