### ISSUE TITLE
Widget not displaying correct temperature

### ISSUE THREAD

**Issue by DJimLut** [Gictorbit/victorconky#4]
When I run the conky config it outputs:
```can't open '/sys/class/thermal/thermal_zone0/temp': No such file or directory``` 
and my temperature just stays at 0 deg Celsius

**Comment by A9G-Data-Droid** [comment]
You would have to post full information about your OS for this issue to be resolvable. That path is correct for Debian variants.

**Comment by DJimLut** [comment]
I am running Linux Mint 20.3 Cinnamon

**Comment by A9G-Data-Droid** [comment]
That's odd. Mint is an Ubuntu derivative, just like my OS. Can you try running this script and see if it outputs good data?

https://github.com/linuxmint/cinnamon-spices-applets/blob/master/Sensors%40claudiux/files/Sensors%40claudiux/scripts/detect_temp.sh

If it does, we could change the method used to pull temperature in conky to match what the Mint team is doing to pull temperature.

**Comment by DJimLut** [comment]
Maybe I'm too new to linux so this is going to sound dumb but when I run sh detect_temp.sh it outputs `detect_temp.sh: 4: Syntax error: "(" unexpected` to the console.

**Comment by A9G-Data-Droid** [comment]
PROTIP: The first line of any shell script should tell you which command interpreter the script was written for. We can tell this script was written for the Bourne Again Shell (BASH) because the first line is:

```
#!/bin/bash
```

When you ran `sh detect_temp.sh` you passed the script to `/bin/sh` which is the old Bourne shell.

Try running the script through bash.

```
/bin/bash detect_temp.sh
```

For more information:
https://linuxhint.com/bin-sh-vs-bin-bash/

**Comment by DJimLut** [comment]
I see. Thanks for your nice and helpful reply. When I run `bash detect_temp.sh` I get a similar message. `ls: cannot access '/sys/class/hwmon/hwmon2/temp*_input': No such file or directory` is output to the console. Even if I run as root

**Comment by A9G-Data-Droid** [comment]
That's odd. Those should be populated by kernel modules. There might be something wrong with your kenrel or the hardware it's trying to read.

In your Conky script file try changing:

`${acpitemp}`

TO

`${hwmon coretemp temp 1}`

**Comment by DJimLut** [comment]
I changed it and still similar output:
```
conky: can't open '/sys/class/hwmon/hwmoncoretemp/temp1_input': No such file or directory
please check your device or remove this var from conky

**Comment by DJimLut** [comment]
How can I check the hardware/kernel to debug why it's not populating that folder? CPU is AMD FX-6300 3.5 GHz 6-Core processor.

**Comment by A9G-Data-Droid** [comment]
That is an important bit of information. It looks like it's not just Linux, it's your chip.

That chip doesn't have a set of normal temperature sensors per core. The one it does have doesn't even report temperature in C, F, or K. It's arbitrary. You're not going to get a good number from it even if you do find the sensor.

https://www.reddit.com/r/pcmasterrace/comments/3vcymu/heres_how_to_correctly_read_the_temperature_of/

I would close this issue as being hardware related and well outside the scope of conky.

**Comment by DJimLut** [comment]
I'll look into AMD Overdrive and research if I could call it with your conky layout. I really like it and would hate to have to change it because of a blank cpu temp module. I see this issue is not with your conky config but with my hardware.
